name: dart_ecommerce
description: A simple Dart e-commerce application using Flutter and Riverpod.
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0' 

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0  
  collection: ^1.17.0

dev_dependencies:
  build_runner: ^2.1.8
  riverpod_generator: ^2.0.0
  lints: ^4.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
